version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: zara-service-db
    environment:
      POSTGRES_USER: postgres_dev
      POSTGRES_PASSWORD: root_dev
      POSTGRES_DB: zara-service-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  testapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testapp_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/zara-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

volumes:
  postgres_data:
